=== ASRRtechnologies/vw-dto-conventions/schemas/vw-project-configurator-schema-project.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://form.nl/conventions.json",
  "type": "object",
  "title": "FORM json file structure conventions",
  "required": [
    "projectName",
    "source",
    "type",
    "options"
  ],
  "properties": {
    "projectName": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "default": "project",
      "examples": [
        "project"
      ],
      "pattern": "project"
    },
    "options": {
      "type": "object",
      "required": [
        "name",
        "blocks"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "logo": {
          "type": "string",
          "enum": [
            "boele_en_van_eesteren",
            "digibase",
            "goossen_te_pas_bouw",
            "stam_de_koning"
          ]
        },
        "contact": {
          "type": "string"
        },
        "blocks": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "name",
              "position",
              "rotation",
              "houses"
            ],
            "properties": {
              "name": {
                "type": "string",
                "default": "Woningblok",
                "pattern": "^(.*)$"
              },
              "position": {
                "type": "object",
                "required": [
                  "x",
                  "y",
                  "z"
                ],
                "properties": {
                  "x": {
                    "type": "number"
                  },
                  "y": {
                    "type": "number"
                  },
                  "z": {
                    "type": "number"
                  }
                }
              },
              "rotation": {
                "type": "object",
                "required": [
                  "x",
                  "y",
                  "z"
                ],
                "properties": {
                  "x": {
                    "type": "number"
                  },
                  "y": {
                    "type": "number"
                  },
                  "z": {
                    "type": "number"
                  }
                }
              },
              "houses": {
                "type": "array",
                "items": {
                  "type": "object",
                  "required": [
                    "name",
                    "house_number",
                    "position",
                    "rotation",
                    "elements"
                  ],
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "house_number": {
                      "type": "integer"
                    },
                    "position": {
                      "type": "object",
                      "required": [
                        "x",
                        "y",
                        "z"
                      ],
                      "properties": {
                        "x": {
                          "type": "number"
                        },
                        "y": {
                          "type": "number"
                        },
                        "z": {
                          "type": "number"
                        }
                      }
                    },
                    "rotation": {
                      "type": "object",
                      "required": [
                        "x",
                        "y",
                        "z"
                      ],
                      "properties": {
                        "x": {
                          "type": "number"
                        },
                        "y": {
                          "type": "number"
                        },
                        "z": {
                          "type": "number"
                        }
                      }
                    },
                    "elements": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "name",
                          "id",
                          "level",
                          "position",
                          "rotation"
                        ],
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "id": {
                            "type": "string",
                            "enum": [
                              "voorgevel",
                              "voorgevel_1e",
                              "zadeldak_links_geen_voorgevel",
                              "zadeldak_links_zonder_voorgevels",
                              "zadeldak_midden_geen_voorgevel",
                              "zadeldak_midden_zonder_voorgevels",
                              "zadeldak_rechts_geen_voorgevel",
                              "zadeldak_rechts_zonder_voorgevels"
                            ]
                          },
                          "level": {
                            "type": "integer"
                          },
                          "position": {
                            "type": "object",
                            "required": [
                              "x",
                              "y",
                              "z"
                            ],
                            "properties": {
                              "x": {
                                "type": "number"
                              },
                              "y": {
                                "type": "number"
                              },
                              "z": {
                                "type": "number"
                              }
                            }
                          },
                          "rotation": {
                            "type": "object",
                            "required": [
                              "x",
                              "y",
                              "z"
                            ],
                            "properties": {
                              "x": {
                                "type": "number"
                              },
                              "y": {
                                "type": "number"
                              },
                              "z": {
                                "type": "number"
                              }
                            }
                          },
                          "elements": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "required": [
                                "type",
                                "position",
                                "width",
                                "height"
                              ],
                              "properties": {
                                "type": {
                                  "type": "string",
                                  "enum": [
                                    "sparing",
                                    "kozijn",
                                    "rollaag",
                                    "vlakvulling",
                                    "dorpel"
                                  ]
                                },
                                "id": {
                                  "type": "string",
                                  "enum": [
                                    "AA01-00",
                                    "BA01-00",
                                    "BA02-00",
                                    "BD01-00",
                                    "BD02-00",
                                    "CA01-00",
                                    "CA02-00",
                                    "CA03-00",
                                    "CA04-00",
                                    "CA05-00",
                                    "CA06-00",
                                    "CA07-00",
                                    "CB01-00",
                                    "CB02-00",
                                    "CB03-00",
                                    "CB04-00",
                                    "CB05-00",
                                    "CB06-00",
                                    "CB07-00",
                                    "CC01-00",
                                    "CC02-00",
                                    "CC03-00",
                                    "CC04-00",
                                    "CC05-00",
                                    "CC06-00",
                                    "CC07-00",
                                    "CD01-00",
                                    "CD02-00",
                                    "CD03-00",
                                    "CD04-00",
                                    "CD05-00",
                                    "CD06-00",
                                    "CD07-00",
                                    "CE01-00",
                                    "CE02-00",
                                    "CE03-00",
                                    "CE04-00",
                                    "CE05-00",
                                    "CE06-00",
                                    "CE07-00",
                                    "CF01-00",
                                    "CF02-00",
                                    "CF03-00",
                                    "CF04-00",
                                    "CF05-00",
                                    "CF06-00",
                                    "CF07-00",
                                    "DA01-00",
                                    "DA02-00",
                                    "DA03-00",
                                    "DA04-00",
                                    "DB01-00",
                                    "DB02-00",
                                    "DB03-00",
                                    "DC01-00",
                                    "DC02-00",
                                    "dorpel",
                                    "EA01-00",
                                    "EA02-00",
                                    "EA03-00",
                                    "EA04-00",
                                    "EA05-00",
                                    "EA06-00",
                                    "EC01-00",
                                    "EC02-00",
                                    "EC03-00",
                                    "EC04-00",
                                    "EC05-00",
                                    "EC06-00",
                                    "FA01-00",
                                    "FA02-00",
                                    "FA03-00",
                                    "FA04-00",
                                    "FB01-00",
                                    "GA01-00",
                                    "GA02-00",
                                    "GA03-00",
                                    "GA04-00",
                                    "GA05-00",
                                    "GA06-00",
                                    "GA07-00",
                                    "HA01-00",
                                    "HA02-00",
                                    "HA03-00",
                                    "HA04-00",
                                    "HA05-00",
                                    "HA06-00",
                                    "HA07-00",
                                    "HB30-00",
                                    "HB31-00",
                                    "HB32-00",
                                    "HB33-00",
                                    "HB34-00",
                                    "HB35-00",
                                    "HB36-00",
                                    "JA01-00",
                                    "JA02-00",
                                    "JA03-00",
                                    "JA04-00",
                                    "JA05-00",
                                    "JA06-00",
                                    "JC31-00",
                                    "JC32-00",
                                    "JC33-00",
                                    "JC34-00",
                                    "JC35-00",
                                    "JC36-00",
                                    "KA01-00",
                                    "KA02-00",
                                    "KA03-00",
                                    "KA04-00",
                                    "KA05-00",
                                    "KA06-00",
                                    "KA07-00",
                                    "luifel",
                                    "NA01-00",
                                    "NA02-00",
                                    "NA03-00",
                                    "NA04-00",
                                    "NA05-00",
                                    "NA06-00",
                                    "NA07-00",
                                    "raam",
                                    "rollaag_horizontaal",
                                    "rollaag_verticaal",
                                    "sparing",
                                    "vlakvulling"
                                  ]
                                },
                                "position": {
                                  "type": "object",
                                  "required": [
                                    "x",
                                    "y",
                                    "z"
                                  ],
                                  "properties": {
                                    "x": {
                                      "type": "number"
                                    },
                                    "y": {
                                      "type": "number"
                                    },
                                    "z": {
                                      "type": "number"
                                    }
                                  }
                                },
                                "width": {
                                  "type": "number"
                                },
                                "height": {
                                  "type": "number"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== ASRRtechnologies/vw-dto-conventions/projectconfiguraties/post_project_gevel_bg&1e_voorbeeld.json
{
    "projectName": "PROJECTNAAM",
    "source": "UWKM",
    "type": "project",
    "options": {
        "name": "PROJECTNAAM",
        "logo": "digibase",
        "contact": "Meneer Man",
        "blocks": [
            {
                "name": "Woningblok#1",
                "position": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                },
                "rotation": {
                    "x": 1,
                    "y": 0,
                    "z": 0
                },
                "houses": [
                    {
                        "name": "Zadeldak Links",
                        "house_number": 1,
                        "position": {
                            "x": 280,
                            "y": 0,
                            "z": 0
                        },
                        "rotation": {
                            "x": 1,
                            "y": 0,
                            "z": 0
                        },
                        "elements": [
                            {
                                "name": "Zadeldak Links Zonder Voorgevels",
                                "id": "zadeldak_links_zonder_voorgevels",
                                "level": 0,
                                "position": {
                                    "x": 0,
                                    "y": 0,
                                    "z": 0
                                },
                                "rotation": {
                                    "x": 1,
                                    "y": 0,
                                    "z": 0
                                }
                            },
                            {
                                "name": "Voorgevel BG",
                                "id": "voorgevel",
                                "level": 0,
                                "position": {
                                    "x": 0,
                                    "y": 0,
                                    "z": 0
                                },
                                "rotation": {
                                    "x": 1,
                                    "y": 0,
                                    "z": 0
                                },
                                "elements": [
                                    {
                                        "type": "kozijn", 
                                        "id": "KA05-00", 
                                        "position": {
                                            "x": 1500,
                                            "y": 70, 
                                            "z": 1145
                                        },
                                        "width": 890,
                                        "height": 1385
                                    },
                                    {
                                        "type": "dorpel",  
                                        "id": "dorpel", 
                                        "position": {
                                            "x": 1500,
                                            "y": 0, 
                                            "z": 1055
                                        },
                                        "width": 890,
                                        "height": 90
                                    },
                                    {
                                        "type": "sparing",
                                        "position": {
                                            "x": 1500,
                                            "y": 0,
                                            "z": 1055
                                        },
                                        "width": 890,
                                        "height": 1475
                                    }
                                ]
                            },
                            {
                                "name": "Voorgevel 1e",
                                "id": "voorgevel_1e",
                                "level": 1,
                                "position": {
                                    "x": 0,
                                    "y": 0,
                                    "z": 0
                                },
                                "rotation": {
                                    "x": 1,
                                    "y": 0,
                                    "z": 0
                                },
                                "elements": [
                                    {
                                        "type": "kozijn", 
                                        "id": "KA05-00", 
                                        "position": {
                                            "x": 1500,
                                            "y": 70, 
                                            "z": 1145
                                        },
                                        "width": 890,
                                        "height": 1385
                                    },
                                    {
                                        "type": "dorpel",  
                                        "id": "dorpel", 
                                        "position": {
                                            "x": 1500,
                                            "y": 0, 
                                            "z": 1055
                                        },
                                        "width": 890,
                                        "height": 90
                                    },
                                    {
                                        "type": "sparing",
                                        "position": {
                                            "x": 1500,
                                            "y": 0,
                                            "z": 1055
                                        },
                                        "width": 890,
                                        "height": 1475
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
}
